version: '2.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 8000:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - mysql