version: '2.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 8000:80
    networks:
      - application
      - example-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - admin
      - example-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - admin
    depends_on:
      - mysql

networks:
  example-network:
    external:
      name: example-network
  admin:
  application:
  other_network: